language: go
sudo: required
dist: trusty
go:
  - "1.9.4"
  - "1.10"

os:
  - linux
  - osx

install:
  - go get github.com/stretchr/testify/assert

script:
  - go test github.com/mchirico/septa/utils
  


